In [1]:
import tensorflow
tensorflow.__version__

'2.0.0'

In [2]:
import numpy as np
import random
random.seed(0)
import warnings
warnings.filterwarnings("ignore")

In [4]:
from tensorflow.keras.datasets import boston_housing
(features, actual_prices) = boston_housing.load_data(test_split = 0)

57344/57026 [==============================] - 0s 2us/step


In [12]:
features[0].shape

(506, 13)

In [15]:
actual_prices[1].shape

(0,)

In [16]:
features[:5]

(array([[1.23247e+00, 0.00000e+00, 8.14000e+00, ..., 2.10000e+01,
         3.96900e+02, 1.87200e+01],
        [2.17700e-02, 8.25000e+01, 2.03000e+00, ..., 1.47000e+01,
         3.95380e+02, 3.11000e+00],
        [4.89822e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
         3.75520e+02, 3.26000e+00],
        ...,
        [1.83377e+00, 0.00000e+00, 1.95800e+01, ..., 1.47000e+01,
         3.89610e+02, 1.92000e+00],
        [3.58090e-01, 0.00000e+00, 6.20000e+00, ..., 1.74000e+01,
         3.91700e+02, 9.71000e+00],
        [2.92400e+00, 0.00000e+00, 1.95800e+01, ..., 1.47000e+01,
         2.40160e+02, 9.81000e+00]]),
 array([15.2, 42.3, 50. , 21.1, 17.7, 18.5, 11.3, 15.6, 15.6, 14.4, 12.1,
        17.9, 23.1, 19.9, 15.7,  8.8, 50. , 22.5, 24.1, 27.5, 10.9, 30.8,
        32.9, 24. , 18.5, 13.3, 22.9, 34.7, 16.6, 17.5, 22.3, 16.1, 14.9,
        23.1, 34.9, 25. , 13.9, 13.1, 20.4, 20. , 15.2, 24.7, 22.2, 16.7,
        12.7, 15.6, 18.4, 21. , 30.1, 15.1, 18.7,  9.6, 31.5, 24.8, 19.1,
   

In [18]:
model = tensorflow.keras.models.Sequential()
model.add(tensorflow.keras.layers.BatchNormalization(input_shape=(13,)))
model.add(tensorflow.keras.layers.Dense(1))

In [19]:
model.compile(optimizer="sgd", loss = "mse")

In [29]:
model.fit(features[0], features[1], epochs = 100, validation_split= 0.3)

Train on 354 samples, validate on 152 samples
Epoch 1/100
354/354 [==============================] - 1s 2ms/sample - loss: 236.8515 - val_loss: 2082.3011
Epoch 2/100
354/354 [==============================] - 0s 124us/sample - loss: 54.6071 - val_loss: 384.1278
Epoch 3/100
354/354 [==============================] - 0s 87us/sample - loss: 43.9958 - val_loss: 131.0491
Epoch 4/100
354/354 [==============================] - 0s 85us/sample - loss: 51.2062 - val_loss: 46.1247
Epoch 5/100
354/354 [==============================] - 0s 85us/sample - loss: 43.7117 - val_loss: 284.4395
Epoch 6/100
354/354 [==============================] - 0s 96us/sample - loss: 58.7224 - val_loss: 32.3588
Epoch 7/100
354/354 [==============================] - 0s 104us/sample - loss: 35.4978 - val_loss: 43.0525
Epoch 8/100
354/354 [==============================] - 0s 118us/sample - loss: 34.0017 - val_loss: 48.9767
Epoch 9/100
354/354 [==============================] - 0s 99us/sample - loss: 35.2649 - val_loss: 

354/354 [==============================] - 0s 96us/sample - loss: 32.7269 - val_loss: 140.1917
Epoch 78/100
354/354 [==============================] - 0s 82us/sample - loss: 43.5161 - val_loss: 42.2730
Epoch 79/100
354/354 [==============================] - 0s 85us/sample - loss: 26.7715 - val_loss: 48.4008
Epoch 80/100
354/354 [==============================] - 0s 87us/sample - loss: 30.7667 - val_loss: 37.8522
Epoch 81/100
354/354 [==============================] - 0s 85us/sample - loss: 29.0669 - val_loss: 37.3115
Epoch 82/100
354/354 [==============================] - 0s 93us/sample - loss: 27.7464 - val_loss: 35.3980
Epoch 83/100
354/354 [==============================] - 0s 90us/sample - loss: 35.1202 - val_loss: 25.4663
Epoch 84/100
354/354 [==============================] - 0s 87us/sample - loss: 28.9672 - val_loss: 31.1471
Epoch 85/100
354/354 [==============================] - 0s 85us/sample - loss: 28.4785 - val_loss: 28.0191
Epoch 86/100
354/354 [===========================

In [47]:
predict_ = np.array([[0.04742,0,12.93,0,0.673,7.03,82.8,3.505,1,276,22,398.9,8.88]])

In [48]:
predict_

array([[4.742e-02, 0.000e+00, 1.293e+01, 0.000e+00, 6.730e-01, 7.030e+00,
        8.280e+01, 3.505e+00, 1.000e+00, 2.760e+02, 2.200e+01, 3.989e+02,
        8.880e+00]])

In [49]:
model.predict(predict_)

array([[19.691418]], dtype=float32)