In [1]:
import numpy as np
import pandas as pd

npmatrix = np.array([[1,2],[3,4]])
npmatrix

array([[1, 2],
       [3, 4]])

In [ ]:
simple_list = [1,2,3]

In [3]:
npmatrix[1,1]

In [6]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.ones(16).reshape(4,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.linspace(0,10,16).reshape(4,4)

array([[ 0.        ,  0.66666667,  1.33333333,  2.        ],
       [ 2.66666667,  3.33333333,  4.        ,  4.66666667],
       [ 5.33333333,  6.        ,  6.66666667,  7.33333333],
       [ 8.        ,  8.66666667,  9.33333333, 10.        ]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
toTrans = np.random.rand(3,3)

In [22]:
np.random.randn(6)

array([-0.4895207 , -1.09361717,  0.77767642,  0.20573303,  0.09717519,
        1.30947341])

In [21]:
np.random.randint(5,21,4)

array([ 6, 20, 17, 10])

In [23]:
sample_array = np.arange(30)
rand_array = np.random.randint(0,100,20)

In [24]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [26]:
rand_array.argmax()

3

In [28]:
sample_array.shape

(30,)

In [29]:
sample_array.dtype

dtype('int32')

In [34]:
toTrans.T

array([[0.80218873, 0.34469648, 0.7898116 ],
       [0.46003827, 0.21311676, 0.42180004],
       [0.47527145, 0.65058309, 0.41869413]])

In [33]:
toTrans

array([[0.80218873, 0.46003827, 0.47527145],
       [0.34469648, 0.21311676, 0.65058309],
       [0.7898116 , 0.42180004, 0.41869413]])

In [35]:
sample_array = np.arange(10,21)

In [36]:
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [37]:
sample_array[8]

18

In [40]:
sample_array [[2,5]]

array([12, 15])

In [43]:
matrix2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])


In [44]:
matrix2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [45]:
matrix2d[2:,2:]

array([[11, 12],
       [15, 16]])