In [1]:
import numpy as np
mylist = [1,2,3]
np.array(mylist)

array([1, 2, 3])

In [2]:
np.array([[1,2,3],[4,5,6],[6,7,8]])

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [4]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [6]:
np.linspace(0,10,100).reshape(20,5)

array([[ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ],
       [ 0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091],
       [ 1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141],
       [ 1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192],
       [ 2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242],
       [ 2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293],
       [ 3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343],
       [ 3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394],
       [ 4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444],
       [ 4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495],
       [ 5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545],
       [ 5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596],
       [ 6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646],
       [ 6.56565657,  6.66666667,  6.7

In [7]:
np.zeros (3)

array([0., 0., 0.])

In [8]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones(3)

array([1., 1., 1.])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.eye (4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.random.rand(5,5)

array([[0.56666671, 0.2955751 , 0.03680297, 0.7023067 , 0.20109703],
       [0.79638196, 0.2956656 , 0.03796567, 0.14783077, 0.77414842],
       [0.94465177, 0.58277234, 0.15843298, 0.38032923, 0.8475629 ],
       [0.60436443, 0.7392089 , 0.59693649, 0.24752048, 0.90408332],
       [0.34158809, 0.52646048, 0.96216275, 0.94189915, 0.79967732]])

In [14]:
np.random.randn(5,4)

array([[-0.46431884,  0.97369311, -1.74773872, -0.18194664],
       [-0.66476761,  0.79948246, -0.55973095,  0.78790475],
       [ 0.70232152,  0.3744331 , -0.49566443, -1.16166405],
       [-0.92370445,  0.87714252,  0.46471947,  0.78032942],
       [ 0.96276075,  0.47182932,  0.3771563 ,  0.07597948]])

In [17]:
np.random.randint(0,101,10).reshape(5,2)

array([[ 5, 15],
       [ 8, 68],
       [76, 88],
       [94, 90],
       [71, 70]])

In [18]:
arr = np.arange(25)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
arr.max()

24

In [22]:
arr.min()

0

In [23]:
arr.sum()

300

In [26]:
arr.std()

7.211102550927978

In [28]:
arr.shape

(25,)

In [29]:
arr.reshape(5,5).shape

(5, 5)

In [30]:
arr.dtype

dtype('int32')

In [31]:
from numpy.random import randint as rnd

In [35]:
rnd(0,5)

2

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
arr[1:4]

array([1, 2, 3])

In [38]:
arr[5:9]

array([5, 6, 7, 8])

In [39]:
mat = arr.reshape(5,5)

In [40]:
mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
arr[5:] = 99

In [42]:
arr

array([ 0,  1,  2,  3,  4, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99])

In [43]:
arr = mat.reshape(25,)

In [44]:
arr

array([ 0,  1,  2,  3,  4, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99])

In [45]:
mat

array([[ 0,  1,  2,  3,  4],
       [99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99]])

In [46]:
arr = np.arange(25)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [48]:
mat

array([[ 0,  1,  2,  3,  4],
       [99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99]])

In [49]:
mat = arr.reshape(5,5)

In [50]:
mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [52]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [55]:
arr_2d[1,]

array([20, 25, 30])

In [57]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [58]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [59]:
arr_2d [arr_2d > 15]

array([20, 25, 30, 35, 40, 45])

In [61]:
arr_2d> 25

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])