In [3]:
import numpy as np
import pandas as pd

In [4]:
npmatrix = np.array(
    [[1,2,3,4],
     [5,6,7,8],
     [9,10,11,12],
     [13,14,15,16]])

In [5]:
npmatrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [7]:
npmatrix[[1,3],2:]

array([[ 7,  8],
       [15, 16]])

In [9]:
arr = npmatrix[npmatrix>2]

In [11]:
arr[arr>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [12]:
arr + arr

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32])

In [13]:
np.sqrt(arr)

array([1.73205081, 2.        , 2.23606798, 2.44948974, 2.64575131,
       2.82842712, 3.        , 3.16227766, 3.31662479, 3.46410162,
       3.60555128, 3.74165739, 3.87298335, 4.        ])

In [14]:
np.exp(arr)

array([2.00855369e+01, 5.45981500e+01, 1.48413159e+02, 4.03428793e+02,
       1.09663316e+03, 2.98095799e+03, 8.10308393e+03, 2.20264658e+04,
       5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
       3.26901737e+06, 8.88611052e+06])

In [15]:
np.log(arr)

array([1.09861229, 1.38629436, 1.60943791, 1.79175947, 1.94591015,
       2.07944154, 2.19722458, 2.30258509, 2.39789527, 2.48490665,
       2.56494936, 2.63905733, 2.7080502 , 2.77258872])

In [16]:
np.sin(arr)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ,
        0.98935825,  0.41211849, -0.54402111, -0.99999021, -0.53657292,
        0.42016704,  0.99060736,  0.65028784, -0.28790332])

In [17]:
np.cos(arr)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029,  0.75390225,
       -0.14550003, -0.91113026, -0.83907153,  0.0044257 ,  0.84385396,
        0.90744678,  0.13673722, -0.75968791, -0.95765948])

In [21]:
np.cos(arr).round(2).std()

0.7288822866245976

In [22]:
np.var(arr)

16.25